//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AgileQuoteAdminEntities : DbContext
    {
        public AgileQuoteAdminEntities()
            : base("name=AgileQuoteAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAddress> tbAddresses { get; set; }
        public DbSet<tbCompany> tbCompanies { get; set; }
        public DbSet<tbCustomerDetail> tbCustomerDetails { get; set; }
        public DbSet<tbCustomerRole> tbCustomerRoles { get; set; }
        public DbSet<tbImageCategory> tbImageCategories { get; set; }
        public DbSet<tbLoginMaintenance> tbLoginMaintenances { get; set; }
        public DbSet<tbMembershipLogin> tbMembershipLogins { get; set; }
        public DbSet<tbUserImage> tbUserImages { get; set; }
    
        public virtual ObjectResult<RoleSelect_Result> RoleSelect(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RoleSelect_Result>("RoleSelect", valueParameter);
        }
    
        public virtual ObjectResult<spGetCollaborators_Result> spGetCollaborators(Nullable<int> companyCode)
        {
            var companyCodeParameter = companyCode.HasValue ?
                new ObjectParameter("companyCode", companyCode) :
                new ObjectParameter("companyCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCollaborators_Result>("spGetCollaborators", companyCodeParameter);
        }
    
        public virtual int spSaveAsNewQuoteAddress(Nullable<int> quoteIdOld, Nullable<int> quoteIdNew)
        {
            var quoteIdOldParameter = quoteIdOld.HasValue ?
                new ObjectParameter("quoteIdOld", quoteIdOld) :
                new ObjectParameter("quoteIdOld", typeof(int));
    
            var quoteIdNewParameter = quoteIdNew.HasValue ?
                new ObjectParameter("quoteIdNew", quoteIdNew) :
                new ObjectParameter("quoteIdNew", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSaveAsNewQuoteAddress", quoteIdOldParameter, quoteIdNewParameter);
        }
    }
}
