//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAddress
    {
        public int Sno { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string AddressType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual tbCustomerDetail tbCustomerDetail { get; set; }
    }
}
