//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBundle
    {
        public tbBundle()
        {
            this.tbQuoteBundleMappings = new HashSet<tbQuoteBundleMapping>();
        }
    
        public int BundleID { get; set; }
        public string BundleName { get; set; }
        public string BundleDescription { get; set; }
        public string BundleType { get; set; }
        public string BundleCategory { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> Warrenty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<decimal> Installation { get; set; }
    
        public virtual ICollection<tbQuoteBundleMapping> tbQuoteBundleMappings { get; set; }
    }
}
