//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCustomerDetail
    {
        public tbCustomerDetail()
        {
            this.tbAddresses = new HashSet<tbAddress>();
            this.tbUserImages = new HashSet<tbUserImage>();
            this.tbLoginMaintenances = new HashSet<tbLoginMaintenance>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string RoleName { get; set; }
        public int CompanyCode { get; set; }
        public bool IsAdminUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<tbAddress> tbAddresses { get; set; }
        public virtual tbCompany tbCompany { get; set; }
        public virtual ICollection<tbUserImage> tbUserImages { get; set; }
        public virtual ICollection<tbLoginMaintenance> tbLoginMaintenances { get; set; }
    }
}
