//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoginMaintenance
    {
        public int MaintenanceId { get; set; }
        public int UserID { get; set; }
        public string LoginEmail { get; set; }
        public string Company { get; set; }
        public string LoginTime { get; set; }
        public string LogoutTime { get; set; }
        public string TimeDuration { get; set; }
    
        public virtual tbCustomerDetail tbCustomerDetail { get; set; }
    }
}
