//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbQuoteQualitativeInformation
    {
        public int QuoteID { get; set; }
        public string Leadtime { get; set; }
        public string WinProbability { get; set; }
        public string ScopeofWork { get; set; }
        public string ExecutiveSummary { get; set; }
        public string PrimaryCompetitor { get; set; }
        public string SellingPrice { get; set; }
        public string PaymentTerms { get; set; }
        public string RiskMitigation { get; set; }
        public string NewRepeatBusiness { get; set; }
        public string AnyOtherComments { get; set; }
    }
}
