//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbQuoteMaterialInstalation
    {
        public int Sno { get; set; }
        public int QuoteID { get; set; }
        public int MaterialID { get; set; }
        public int Quantity { get; set; }
        public decimal IntallationCharges { get; set; }
        public decimal TotalCost { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tbQuote tbQuote { get; set; }
    }
}
