//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRentalProduct
    {
        public tbRentalProduct()
        {
            this.tbQuoteRentalProductMappings = new HashSet<tbQuoteRentalProductMapping>();
        }
    
        public int RentalProductsID { get; set; }
        public string RentalProductsName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Warrenty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<tbQuoteRentalProductMapping> tbQuoteRentalProductMappings { get; set; }
    }
}
